#!/bin/bash

status_char=( '-' '\' '|' '/' )

progress() {
    while true; do
        for i in "${status_char[@]}"
        do
	    idesh wm title "mk: $@ [$i] ..."
	    sleep 0.5
        done
    done
}

if [ -n "${NNN_PLUG}" ]; then
    idesh wm create "idesh mk -c $PWD $@"
    exit
fi

options_prompt=n

while [ $# -gt 0 ]; do
    case $1 in
        -c)
           cd $2
           shift 1
	   ;;
        -p)
           options_prompt=y
	   ;;
	 *)
           break
           ;;
    esac
    shift 1
done

tmpfile=$(mktemp /tmp/idesh-mk.XXXXXX)

mime_type="*"

if [ -e "$PWD/$1" ]; then
    mime_type=$(file -biL $1 2>/dev/null)
fi

set -o pipefail

trap "rm -f $tmpfile; exit;" SIGINT SIGTERM

options=""

while true; do
    idesh wm title "mk: $@ $options ..."

    if [ "${options_prompt}" == "y" ]; then
        read -p "options: " options
	options_prompt=n
    fi

    cmdl="$@ $options"

    progress "$cmdl" &
    status_pid=$!

    case $mime_type in
        *x-makefile*)
                    sh -c "make -f $cmdl" 2>&1 | tee $tmpfile
                    ret=$?
                    ;;

                   *)
                    if [ -e "$1" ]; then
                        sh -c "./$cmdl" 2>&1 | tee $tmpfile
                        ret=$?
                    else
                        sh -c "$cmdl" 2>&1 | tee $tmpfile
                        ret=$?
                    fi
                    ;;
    esac

    kill $status_pid

    if [ $ret -ne 0 ]; then
	idesh wm title "mk: $cmdl [ERROR]"
        vim -S ${IDESH_PATH}/gr/vim/qfix.vim -c ":cfile $tmpfile"
    else
	idesh wm title "mk: $cmdl [OK]"
    fi

    echo "[Press ENTER to continue, 'c' change command line options, Ctrl-C for exit]"
    read -n1 key

    if [ "$key" == "c" ]; then
        options_prompt="y"
        echo ""
    fi
done

rm -f $tmpfile
