#! /bin/bash

idesh wm title "grep:"

mkdir -p ${HOME}/.cache/idesh/search
IDESH_GREP_RECENT=${HOME}/.cache/idesh/search/recent

touch ${IDESH_GREP_RECENT}

grep_recent() {
    READLINE_LINE=$(cat ${IDESH_GREP_RECENT} | fzy)
}
bind -x '"\C-r":grep_recent' 2> /dev/null

IDESH_GREP_CMD="grep -rnI --exclude-dir=.git"

echo "[Ctrl-R to select recent searched words]"
echo ""
read -e -p 'grep: ' search

idesh wm title "grep: $search"

IDESH_GREP_TMP=/tmp/idesh-grep.$$

${IDESH_GREP_CMD} "${search}" > ${IDESH_GREP_TMP}
if [ $? -ne 0 ]; then
    rm -f ${IDESH_GREP_TMP}
    echo "No matches found :-(, press Enter to exit"
    read
    exit
fi

if [ -s ${IDESH_GREP_RECENT} ]; then
    sed -i -e "0,/^/s//${search}\n/;20d" ${IDESH_GREP_RECENT}
else
    echo ${search} > ${IDESH_GREP_RECENT}
fi

sort ${IDESH_GREP_RECENT} | uniq > ${HOME}/.cache/idesh/search/recent.$$
mv ${HOME}/.cache/idesh/search/recent.$$ ${IDESH_GREP_RECENT}

vim -S ${IDESH_PATH}/ed/vim/qfix.vim -c ":cfile ${IDESH_GREP_TMP}"
