.PHONY: all install

all:
	@

install:
	$(INSTALL) -D vim/search.vim $(IDESH_PATH)/gr/vim/search.vim
	$(INSTALL) -Dm 0755 vim/grep $(IDESH_PATH)/gr/vim/grep
	$(INSTALL) -Dm 0755 main $(IDESH_PATH)/gr/main
