#!/bin/bash

IDESH_CSCOPE_PATH="${PWD}/.idesh/cs/cscope"
IDESH_CS_RECENT="${PWD}/.idesh/cs/recent"

do_index() {
    mkdir $IDESH_CSCOPE_PATH -p

    find . \
	    -name '*.aidl' \
	    -o -name '*.cc' \
	    -o -name '*.h' \
	    -o -name '*.c' -o \
	    -name '*.cpp' -o \
	    -name '*.java' \
	    -o -name '*.py' > $IDESH_CSCOPE_PATH/cscope.files

    cscope -bkq -i $IDESH_CSCOPE_PATH/cscope.files \
	    -f $IDESH_CSCOPE_PATH/cscope.db
}

select_recent() {
    READLINE_LINE=$(cat ${IDESH_CS_RECENT} | fzy)
}

do_find() {
    mkdir $IDESH_CSCOPE_PATH -p

    touch ${IDESH_CS_RECENT}

    bind -x '"\C-r":select_recent' 2> /dev/null

    ctype="0"

    case $1 in
        -s) ctype="0"; shift 1;;
	-g) ctype="1"; shift 1;;
	-d) ctype="2"; shift 1;;
	-c) ctype="3"; shift 1;;
	-i) ctype="8"; shift 1;;
	-a) ctype="9"; shift 1;;
    esac

    idesh wm title "symbol:"

    search=$1
    if [ $# -eq 0 ]; then
        echo "[Ctrl-R to select recent searched symbol]"
        echo ""
        read -e -p 'symbol: ' search
    fi

    idesh wm title "symbol: $search"

    IDESH_CS_TMP=/tmp/idesh-cs.$$

    IDESH_CS_CMD="cscope -k -i ${IDESH_CSCOPE_PATH}/cscope.files -f ${IDESH_CSCOPE_PATH}/cscope.db"
    ${IDESH_CS_CMD} -L$ctype "${search}" |\
	    awk '{ printf "%s:%s: <%s>", $1,$3,$2; $1=$2=$3=""; print}' > ${IDESH_CS_TMP}

    if [ -s "${IDESH_CS_RECENT}" ]; then
        sed -i -e "0,/^/s//${search}\n/;20d" ${IDESH_CS_RECENT}
    else
        echo ${search} > ${IDESH_CS_RECENT}
    fi

    sort ${IDESH_CS_RECENT} | uniq > ${PWD}/.idesh/cs/recent.$$
    mv ${PWD}/.idesh/cs/recent.$$ ${IDESH_CS_RECENT}

    vim -S ${IDESH_PATH}/ed/vim/qfix.vim -c ":cfile ${IDESH_CS_TMP}"
}

while [ $# -gt 0 ]; do
    case "$1" in
        "index")
                do_index $@
                exit $?
                ;;
	"find")
                shift 1
                do_find $@
                exit $?
		;;
    esac
    shift 1
done
