#!/usr/bin/env bash

new_window=y

if [ "$1" == "-n" ]; then
    new_window=n
    shift 1
fi

if [ -n "$2" ]; then
    line=" +$2"
else
    line=""
fi

cwd=$(idesh wm getcwd)

title="${1/#${cwd}\//}"
title="${title/#\.\//}"

cmd="vim -S ${IDESH_PATH}/ed/vim/idesh.vim ${1}${line}"

if [ "${new_window}" == "y" ]; then
    idesh wm create -t "edit:${title}" "${cmd}" 
else
    $cmd
fi
