#!/usr/bin/env bash

if [ -n "$2" ]; then
    line=" +$2"
else
    line=""
fi

cwd=$(idesh wm getcwd)

title="${1/#${cwd}\//}"
title="${title/#\.\//}"

idesh wm create -t "edit:${title}" "vim -S ${IDESH_PATH}/ed/vim/idesh.vim ${1}${line}"
