#!/usr/bin/env bash

if [ -z "$EDITOR" ]; then
    echo 'ERROR: $EDITOR is not set' | ${PAGER:-less}
    exit 2
fi

if [ -n "$2" ]; then
    line=" +$2"
else
    line=""
fi

cwd=$(idesh wm getcwd)

title="${1/#${cwd}\//}"
title="${title/#\.\//}"

idesh wm create -t "${title}" ${EDITOR} "${1}${line}"
