.PHONY: all install

all:
	@

install:
	$(INSTALL) -Dm 0755 apply $(IDESH_PATH)/vc/apply
	$(INSTALL) -Dm 0755 init $(IDESH_PATH)/vc/init
	$(INSTALL) -Dm 0755 main $(IDESH_PATH)/vc/main
	$(INSTALL) -Dm 0755 tig/tigrc $(IDESH_PATH)/vc/tig/tigrc
