#!/bin/sh

copy_put() {
    local in="-"

    if [ "$1" == "-f" ]; then
        if [ -s "$2" ]; then
            in="$2"
        fi
    else
        return
    fi

    echo "copybuf put" > ${DVTM_CMD_FIFO}
    cat "$in" > ${DVTM_CPY_FIFO}
}

copy_edit() {
    edit=/tmp/idesh-copy-edit.$$
    dvtm-cmd copybuf get > $edit
    idesh-ed $edit
    echo "copybuf put" > ${DVTM_CMD_FIFO}
    cat "$edit" > ${DVTM_CPY_FIFO}
}

case "$1" in
    "put")
         shift 1
	 copy_put $@
         ;;
    "get")
         dvtm-cmd copybuf get
	 ;;
    "edit")
         copy_edit
         ;;
esac
