#!/usr/bin/env sh

if [ -z "$DVTM_CMD_FIFO" ]; then
    echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
    exit 2
fi

cwd="$PWD"

if [ "${1}" == "-c" ]; then
   cwd=$2 
   shift 2
fi

echo "create \"${@}\" \"\" $cwd" > ${DVTM_CMD_FIFO}
