#!/usr/bin/env sh

# Description: Execute command in new window
#
# Shell: POSIX compliant
# Authors: Vadym Kochan <vadimj@gmail.com>

if [ -z "$DVTM_CMD_FIFO" ]; then
    echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
    exit 2
fi

echo "create \"${@}\" \"\" $CWD" > ${DVTM_CMD_FIFO}
