#!/usr/bin/env sh

if [ -z "$DVTM_CMD_FIFO" ]; then
    echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
    exit 2
fi

cwd="$PWD"

while [ $# -gt 0 ]; do
    case ${1} in
        "-c")
            cwd=$2 
            shift 2
	    ;;

        "-t")
            title=$2 
            shift 2
	    ;;

	   *)
            break
            ;;
    esac
done

echo "create \"${@}\" \"${title}\" $cwd" > ${DVTM_CMD_FIFO}
