#!/usr/bin/env sh

if [ -z "$EDITOR" ]; then
    echo 'ERROR: $EDITOR is not set' | ${PAGER:-less}
    exit 2
fi
if [ -z "$DVTM_CMD_FIFO" ]; then
    echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
    exit 2
fi

printf "setlayout \"[ ]\"\n" > ${DVTM_CMD_FIFO}

sel=$(find -type f -not \( -path '*/\.git/*' -prune \) | fzy -s -l 20)

printf "setlayout\n" > ${DVTM_CMD_FIFO}

if [ -n "${sel}" ]; then
    idesh wm open $sel
fi
