#!/bin/sh

export DVTM_CMD_FIFO=${IDESH_RUN_PATH}/dvtm-cmd-fifo
export DVTM_EVT_FIFO=${IDESH_RUN_PATH}/dvtm-evt-fifo
DVTM_SCRIPTS=${IDESH_PATH}/wm/dvtm

while [ $# -ne 0 ]; do
    case $1 in
        -c)
          cmd=${2}
          shift 2
          ${DVTM_SCRIPTS}/${cmd} $@
	  exit $?
          ;;
    esac
    shift
done

mkfifo ${DVTM_CMD_FIFO}
mkfifo ${DVTM_EVT_FIFO}

printf "setmfact 0.25\ncreate \"idesh fs\"\nsetsticky\n" > ${DVTM_CMD_FIFO} &

DVTM_GIT_VIEW_CMD=$(printf "^Xgv:c:create \"tig\" \"git: commits\"")
DVTM_GIT_LOG_CMD=$(printf "^Xgl:c:create \"tig log\" \"git: log\"")
DVTM_GIT_STATUS_CMD=$(printf "^Xgs:c:create \"tig status\" \"git: status\"")
DVTM_GIT_REFS_CMD=$(printf "^Xgr:c:create \"tig refs\" \"git: refs\"")
DVTM_FS_SHOW_CMD=$(printf "^Xfm:c:create \"idesh fs\"")
DVTM_FZ_OPEN_CMD=$(printf "^Xff:c:create \"idesh fs -c fzy-open\" fzy-open")
DVTM_GREP_CMD=$(printf "^Xfg:c:create \"idesh gr\"")

mkdir ${IDESH_RUN_PATH}/tag

for t in {1..5}; do
    mkdir ${IDESH_RUN_PATH}/tag/$t
    ln -sf ${PWD} ${IDESH_RUN_PATH}/tag/$t/cwd
done

ln -sf ${IDESH_RUN_PATH}/tag/1 ${IDESH_RUN_PATH}/tag/current

${IDESH_PATH}/wm/${IDESH_WM}/events &
DVTM_EVENTS_PID=$!

dvtm -c ${DVTM_CMD_FIFO} -e ${DVTM_EVT_FIFO}\
	-b "${DVTM_GIT_VIEW_CMD}" \
	-b "${DVTM_GIT_LOG_CMD}" \
	-b "${DVTM_GIT_STATUS_CMD}" \
	-b "${DVTM_GIT_REFS_CMD}" \
	-b "${DVTM_FS_SHOW_CMD}" \
	-b "${DVTM_FZ_OPEN_CMD}" \
	-b "${DVTM_GREP_CMD}"

kill ${DVTM_EVENTS_PID} 2> /dev/null
