#!/bin/sh

export DVTM_STATUS_FIFO=${IDESH_RUN_PATH}/dvtm-status-fifo
export DVTM_CMD_FIFO=${IDESH_RUN_PATH}/dvtm-cmd-fifo
export DVTM_EVT_FIFO=${IDESH_RUN_PATH}/dvtm-evt-fifo
export DVTM_COPY_EDITOR="dvtm-copy"
DVTM_SCRIPTS=${IDESH_PATH}/wm/dvtm

if [ $# -ne 0 ]; then
    cmd=${1}
    shift 1
    ${DVTM_SCRIPTS}/${cmd} $@
    exit $?
fi

mkfifo ${DVTM_STATUS_FIFO}
mkfifo ${DVTM_CMD_FIFO}
mkfifo ${DVTM_EVT_FIFO}

dvtm_init() {
cat << EOF > ${DVTM_CMD_FIFO}
setminimized align vert
setstatus align left
setmfact 0.25
create "idesh fs"
setsticky on
EOF

if [ -n "${IDESH_INIT_CMD}" ]; then
    echo "${IDESH_INIT_CMD}" > ${DVTM_CMD_FIFO}
fi
if [ -n "${IDESH_INIT_SCRIPT}" ]; then
    sh -c "${IDESH_INIT_SCRIPT}"
fi
}

dvtm_init &

DVTM_GIT_VIEW_CMD=$(printf "^Xgv:c:create \"tig\" \"git: commits\"")
DVTM_GIT_LOG_CMD=$(printf "^Xgl:c:create \"tig log\" \"git: log\"")
DVTM_GIT_STATUS_CMD=$(printf "^Xgs:c:create \"tig status\" \"git: status\"")
DVTM_GIT_REFS_CMD=$(printf "^Xgr:c:create \"tig refs\" \"git: refs\"")
DVTM_FS_SHOW_CMD=$(printf "^Xft:c:create \"idesh fs\"")
DVTM_FZ_OPEN_CMD=$(printf "^Xff:c:create \"idesh fs fzy-open\" fzy-open")
DVTM_GREP_CMD=$(printf "^Xfs:c:create \"idesh gr\"")
DVTM_RUN_CMD=$(printf "^Xr:c:create \"idesh wm run\"" \"\")
DVTM_CS_INDEX_CMD=$(printf "^XcI:c:create \"idesh cs index\"" \"\")
DVTM_CS_SYMB_CMD=$(printf "^Xcs:c:create \"idesh cs find -s\"" \"\")
DVTM_CS_DEF_CMD=$(printf "^Xcg:c:create \"idesh cs find -g\"" \"\")
DVTM_CS_CALLS_CMD=$(printf "^Xcd:c:create \"idesh cs find -d\"" \"\")
DVTM_CS_CALLED_CMD=$(printf "^Xcc:c:create \"idesh cs find -c\"" \"\")
DVTM_CS_INCLUD_CMD=$(printf "^Xci:c:create \"idesh cs find -i\"" \"\")

mkdir ${IDESH_RUN_PATH}/tag

for t in {1..9}; do
    mkdir ${IDESH_RUN_PATH}/tag/$t
    ln -nsf ${PWD} ${IDESH_RUN_PATH}/tag/$t/cwd
done

ln -nsf ${IDESH_RUN_PATH}/tag/1 ${IDESH_RUN_PATH}/tag/current

while true; do
    cwd=$(realpath ${IDESH_RUN_PATH}/tag/current/cwd)
    branch="$(git --git-dir="${cwd}/.git" rev-parse --abbrev-ref HEAD 2> /dev/null)"
    [ -n "${branch}" ] && branch=" (${branch})"
    cwd="${cwd/#$HOME/\~}"
    echo "$cwd$branch"
    sleep 2
done > ${DVTM_STATUS_FIFO} &
DVTM_STATUS_PID=$!

${IDESH_PATH}/wm/${IDESH_WM}/events &
DVTM_EVENTS_PID=$!

dvtm -c ${DVTM_CMD_FIFO} -e ${DVTM_EVT_FIFO} -s ${DVTM_STATUS_FIFO} \
	-b "${DVTM_GIT_VIEW_CMD}" \
	-b "${DVTM_GIT_LOG_CMD}" \
	-b "${DVTM_GIT_STATUS_CMD}" \
	-b "${DVTM_GIT_REFS_CMD}" \
	-b "${DVTM_FS_SHOW_CMD}" \
	-b "${DVTM_FZ_OPEN_CMD}" \
	-b "${DVTM_GREP_CMD}" \
	-b "${DVTM_RUN_CMD}" \
	-b "${DVTM_CS_INDEX_CMD}" \
	-b "${DVTM_CS_SYMB_CMD}" \
	-b "${DVTM_CS_DEF_CMD}" \
	-b "${DVTM_CS_CALLS_CMD}" \
	-b "${DVTM_CS_CALLED_CMD}" \
	-b "${DVTM_CS_INCLUD_CMD}"


kill ${DVTM_EVENTS_PID} 2> /dev/null
kill ${DVTM_STATUS_PID} 2> /dev/null
