#!/usr/bin/env bash

if [ -z "$EDITOR" ]; then
    echo 'ERROR: $EDITOR is not set' | ${PAGER:-less}
    exit 2
fi
if [ -z "$DVTM_CMD_FIFO" ]; then
    echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
    exit 2
fi

if [ -n "$2" ]; then
    line=" +$2"
else
    line=""
fi

title="${1/#${PWD}\//}"
title="${title/#\.\//}"

printf "create \"$EDITOR ${1}${line}\" ${title} ${PWD}\n" > ${DVTM_CMD_FIFO}
