#!/usr/bin/env sh

if [ -z "$DVTM_CMD_FIFO" ]; then
    echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
    exit 2
fi
if [ -z "$NNN_PIPE" ]; then
    echo 'ERROR: $NNN_PIPE is not set' | ${PAGER:-less}
    exit 2
fi

idesh wm setmax on

sel=$(find -type d -not \( -path '*/\.git*' -prune \) | fzy -s -l 20)

idesh wm setmax off

if [ -n "${sel}" ]; then
    path=$(readlink -f $sel)
    printf "0c$path" > "$NNN_PIPE"
fi
