#!/bin/sh

export NNN_PLUG='m:_idesh mk $nnn*;s:_idesh gr*;c:_idesh fs setcwd*;f:_idesh fs fzy-open*;d:_idesh fs fzy-cd*'
export NNN_OPENER="${IDESH_PATH}/wm/${IDESH_WM}/open"

while [ $# -ne 0 ]; do
    case $1 in
	"fzy-cd")
		cmd=${1}
		shift 1
		${IDESH_PATH}/fs/${IDESH_FS}/${IDESH_WM}/${cmd} $@
		exit $?
		;;

	       *)
		idesh wm $@
		exit $?
		;;
    esac
    shift
done

nnn -c
